name: one_uikit
description: "A comprehensive Flutter UI Kit with reusable components, icons, and utilities for 1APP project"
version: 0.0.1
homepage: https://github.com/sapar-io/one_uikit
repository: https://github.com/sapar-io/one_uikit
issue_tracker: https://github.com/sapar-io/one_uikit/issues
documentation: https://github.com/sapar-io/one_uikit#readme

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  logger: ^2.6.1
  multi_dropdown: ^3.0.1
  phone_form_field: ^10.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/